# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: screenservice.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='screenservice.proto',
  package='screenservice',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13screenservice.proto\x12\rscreenservice\"\xa2\x01\n\rScreenRequest\x12\r\n\x05line1\x18\x01 \x01(\t\x12\r\n\x05line2\x18\x02 \x01(\t\x12\r\n\x05line3\x18\x03 \x01(\t\x12\r\n\x05line4\x18\x04 \x01(\t\x12\r\n\x05line5\x18\x05 \x01(\t\x1a\x46\n\x07Timeout\x12\x14\n\x0creturnScreen\x18\x01 \x01(\t\x12\x0e\n\x06length\x18\x02 \x01(\x05\x12\x15\n\rshowCountdown\x18\x03 \x01(\x05\"1\n\x0eScreenResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2[\n\x0cScreenServer\x12K\n\nSendScreen\x12\x1c.screenservice.ScreenRequest\x1a\x1d.screenservice.ScreenResponse\"\x00\x62\x06proto3'
)




_SCREENREQUEST_TIMEOUT = _descriptor.Descriptor(
  name='Timeout',
  full_name='screenservice.ScreenRequest.Timeout',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='returnScreen', full_name='screenservice.ScreenRequest.Timeout.returnScreen', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='length', full_name='screenservice.ScreenRequest.Timeout.length', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='showCountdown', full_name='screenservice.ScreenRequest.Timeout.showCountdown', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=201,
)

_SCREENREQUEST = _descriptor.Descriptor(
  name='ScreenRequest',
  full_name='screenservice.ScreenRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='line1', full_name='screenservice.ScreenRequest.line1', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='line2', full_name='screenservice.ScreenRequest.line2', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='line3', full_name='screenservice.ScreenRequest.line3', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='line4', full_name='screenservice.ScreenRequest.line4', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='line5', full_name='screenservice.ScreenRequest.line5', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_SCREENREQUEST_TIMEOUT, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=201,
)


_SCREENRESPONSE = _descriptor.Descriptor(
  name='ScreenResponse',
  full_name='screenservice.ScreenResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='screenservice.ScreenResponse.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='screenservice.ScreenResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=203,
  serialized_end=252,
)

_SCREENREQUEST_TIMEOUT.containing_type = _SCREENREQUEST
DESCRIPTOR.message_types_by_name['ScreenRequest'] = _SCREENREQUEST
DESCRIPTOR.message_types_by_name['ScreenResponse'] = _SCREENRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ScreenRequest = _reflection.GeneratedProtocolMessageType('ScreenRequest', (_message.Message,), {

  'Timeout' : _reflection.GeneratedProtocolMessageType('Timeout', (_message.Message,), {
    'DESCRIPTOR' : _SCREENREQUEST_TIMEOUT,
    '__module__' : 'screenservice_pb2'
    # @@protoc_insertion_point(class_scope:screenservice.ScreenRequest.Timeout)
    })
  ,
  'DESCRIPTOR' : _SCREENREQUEST,
  '__module__' : 'screenservice_pb2'
  # @@protoc_insertion_point(class_scope:screenservice.ScreenRequest)
  })
_sym_db.RegisterMessage(ScreenRequest)
_sym_db.RegisterMessage(ScreenRequest.Timeout)

ScreenResponse = _reflection.GeneratedProtocolMessageType('ScreenResponse', (_message.Message,), {
  'DESCRIPTOR' : _SCREENRESPONSE,
  '__module__' : 'screenservice_pb2'
  # @@protoc_insertion_point(class_scope:screenservice.ScreenResponse)
  })
_sym_db.RegisterMessage(ScreenResponse)



_SCREENSERVER = _descriptor.ServiceDescriptor(
  name='ScreenServer',
  full_name='screenservice.ScreenServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=254,
  serialized_end=345,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendScreen',
    full_name='screenservice.ScreenServer.SendScreen',
    index=0,
    containing_service=None,
    input_type=_SCREENREQUEST,
    output_type=_SCREENRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SCREENSERVER)

DESCRIPTOR.services_by_name['ScreenServer'] = _SCREENSERVER

# @@protoc_insertion_point(module_scope)
